version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - taskflow-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://taskflow:taskflow_password@db:3306/taskflow
      - SECRET_KEY=your_secret_key_here
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=your_email@gmail.com
      - MAIL_PASSWORD=your_app_password
    networks:
      - taskflow-network

  db:
    image: mariadb:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=taskflow
      - MYSQL_USER=taskflow
      - MYSQL_PASSWORD=taskflow_password
    volumes:
      - taskflow_data:/var/lib/mysql
    networks:
      - taskflow-network

volumes:
  taskflow_data:

networks:
  taskflow-network:
    external: true
